version: '3'
services:
    mysql1:
        container_name: mysql1
        image: mysql:5.7
        networks:
            testing_net:
                ipv4_address: 172.28.1.1
        expose:
            - '3306'
        restart: always
        env_file: db.env
        volumes:
            - db_data1:/var/lib/mysql
    mysql2:
        container_name: mysql2
        image: mysql:5.7
        networks:
            testing_net:
                ipv4_address: 172.28.1.2
        expose:
            - '3306'
        env_file: db.env
        volumes:
            - db_data2:/var/lib/mysql
    mysql3:
        container_name: mysql3
        image: mysql:5.7
        networks:
            testing_net:
                ipv4_address: 172.28.1.3
        expose:
            - '3306'
        env_file: db.env
        volumes:
            - db_data3:/var/lib/mysql
    proxysql:
        container_name: proxysql
        build:
            dockerfile: Dockerfile
            context: './bin/'
        volumes:
            - db_data4:/var/lib/mysql
        networks:
            testing_net:
                ipv4_address: 172.28.1.4
        ports: 
            - '6032:6032'
        tty: true
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
volumes:
  db_data1:
    driver: local
  db_data2:
    driver: local
  db_data3:
    driver: local
  db_data4:
    driver: local